task 10
pavels3579/ror pull request #10
Opened 2019-01-24 19:48 UTC by pavels3579

2019-01-25 05:04 UTC, max-underthesun commented on app/helpers/application_helper.rb
> +  end
ТЗ: "Создайте хэлпер для flash сообщений"
имется в виду хелпер, который будет что-то делать полезное ) суть твоего хелпера не очень ясна
и второй его недостаток - ты его не используешь )
нужно написать хелпер, который будет возвращать `html` с нужным сообщением и "правильным" `css`
и использовать этот хелпер во вьюхах

у тебя в `sessions/_form` есть такой код:
```html
  <% if flash[:alert] %>
    <%= content_tag :p, flash[:alert], class: 'flash alert' %>
  <% end %>
```
надо на его основе сделать хелпер и пользоваться им

2019-01-25 05:04 UTC, max-underthesun commented on config/routes.rb
> +  get :signout, to: 'sessions#destroy'
соблюдай конвенции REST: удаление ресурса (сессии) логично делать через DELETE

2019-01-25 05:04 UTC, max-underthesun commented on config/routes.rb
> +  get :signout, to: 'sessions#destroy'
к тому же во вьюхе у тебя верно указан метод: 
```html
<%= link_to 'Exit', sign_out, method: :delete %>
```
отсюда и ошибка

2019-01-25 05:04 UTC, max-underthesun commented on app/views/layouts/_header.html.erb
> +<% end %>
в хелпере `link_to` вторым аргументом должен идти путь
у тебя полностью корректно путь указан только для первой ссылки: `tests_path`
две последних ссылки будет правильней записать не через `_url`, а через `_path`
а в ссылку `Exit` вместо пути передан вызов метода `sign_out` из хелпера `app/helpers/sessions_helper.rb`

2019-01-25 05:04 UTC, max-underthesun commented on app/controllers/tests_controller.rb
> +  #before_action :authenticate_user!
а почему здесь закомментирован коллбек?

2019-01-25 05:04 UTC, max-underthesun commented on app/controllers/application_controller.rb
> +
не нашел реализации ТЗ: "С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально"

2019-01-25 05:04 UTC, max-underthesun commented on app/models/user.rb
> +                    format: { with: /\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,6}/, message: "it is not correct email" }
лучше использовать какую-нибудь совсем несложную регулярку
по поводу использования "навороченных решений" есть вот [такая статья](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/)

2019-01-25 05:04 UTC, max-underthesun commented on app/models/user.rb
> +                    format: { with: /\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,6}/, message: "it is not correct email" }
если оставлять то, что есть, то правильно будет вынести в константу (к примеру `EMAIL_REGEXP`), чтоб не пугаться при взгляде на эту валидацию ))

2019-01-25 05:04 UTC, max-underthesun commented on app/controllers/tests_controller.rb
> +    @user = current_user
в общем-то `@user` больше вообще не нужен в контроллере
правильно будет просто везде использовать `current_user`

2019-01-25 15:17 UTC, iBublik requested changes

2019-01-25 15:17 UTC, iBublik commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
Это больше не нужно

2019-01-25 15:17 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +      if session[:user_path]
Можно так делать - `session[:user_path] || tests_path`
Еще лучше будет сразу удалить данные из сессии, чтоб не болтались там. Метод `delete` удаляет данные и тут же возвращает удаленно значение - используй этой

2019-01-25 15:17 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
Для удаления используй `delete`

2019-01-25 15:17 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +    cookies.delete(:user_id)
А это зачем?

2019-01-25 15:17 UTC, iBublik commented on app/controllers/tests_controller.rb
> +    @user = current_user
> в общем-то `@user` больше вообще не нужен в контроллере
> правильно будет просто везде использовать `current_user`

Актуально

2019-01-25 15:17 UTC, iBublik commented on app/helpers/application_helper.rb
> +  end
> ТЗ: "Создайте хэлпер для flash сообщений"
> имется в виду хелпер, который будет что-то делать полезное ) суть твоего хелпера не очень ясна
> и второй его недостаток - ты его не используешь )
> нужно написать хелпер, который будет возвращать `html` с нужным сообщением и "правильным" `css`
> и использовать этот хелпер во вьюхах
> 
> у тебя в `sessions/_form` есть такой код:
> 
> ```
>   <% if flash[:alert] %>
>     <%= content_tag :p, flash[:alert], class: 'flash alert' %>
>   <% end %>
> ```
> 
> надо на его основе сделать хелпер и пользоваться им

Актуально

2019-01-25 15:17 UTC, iBublik commented on app/models/user.rb
> +require 'digest/sha1'
Это можно убрать

2019-01-25 15:17 UTC, iBublik commented on app/views/layouts/_header.html.erb
> +  <%= link_to 'Login', login_path, method: :get %>
`method: :get` можно не указывать - это дефолтное значение

2019-01-25 15:17 UTC, iBublik commented on config/routes.rb
> +  resources :sessions, only: %i[create delete destroy]
delete и destroy не нужны

2019-01-26 19:27 UTC, max-underthesun commented on app/controllers/sessions_controller.rb
> +      redirect_to session.delete("user_path") || test_path
- а почему ключ - строка, а не символ?
- редирект на второй путь не сработает, потому что путь `test_path` требует объект класса `Test`
- чаще всего по умолчанию редиректят на "рут паф"

2019-01-26 19:27 UTC, max-underthesun commented on app/controllers/sessions_controller.rb
> +    session.delete("user_id")
лучше все таки символ

2019-01-26 19:27 UTC, max-underthesun commented on app/controllers/sessions_controller.rb
> +  def delete; end
а это что за экшен и зачем он здесь?

2019-01-26 19:27 UTC, max-underthesun commented on app/helpers/application_helper.rb
> +  end
здесь более правильно было бы принимать в аргументах `type`
потому что флеш-сообщения могут быть разных типов, а этот хелпер вернет сообщение, только если это `:alert`
хотелось бы чтобы возвращалось сообщение любого типа (если оно есть - и "если оно есть" - стоит проверять в хелпере)
класс будет правильно вычислять (конструировать) с помощью того же пришедшего в аргументах значения `type`
так хелпер станет более универсальным и полезным

2019-01-26 19:27 UTC, max-underthesun commented on config/routes.rb
> +  get 'users/new'
зачем эти строки здесь?
роуты для этих пар контроллер/экшен определены ниже

2019-01-27 17:40 UTC, merged