task 8
pavels3579/ror pull request #8
Opened 2019-01-15 21:07 UTC by pavels3579

2019-01-16 05:27 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    @questions = Question.all
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами - в этом контроллере этот экшен не нужен, индекс вопросов конкретного теста должен выводиться на странице этого теста

2019-01-16 05:27 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
вот этот код повторяется несколько раз в контроллере
явный признак, что нужно написать `before_action`

2019-01-16 05:27 UTC, max-underthesun commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
повторяющийся код

2019-01-16 05:27 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path
когда уберешь "индекс" здесь редирект правильно будет сделать на страницу теста

2019-01-16 05:27 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path
метод `question_params` должен выглядеть так:
```ruby
def question_params
  params.require(:question).permit(:body)
end
```
ссылка на ассоциацию, те. `:test_id` не приходит под ключом `:question`
она приходит в параметрах вне этого ключа и ее не нужно "пермитить"

в отличие от формы для теста, где "категори ай-ди" выбирается селектором, здесь нужно создавать вопрос сразу для определенного теста, поэтому "тест ай-ди" нужно передавать в пути, а не в параметрах вопроса

2019-01-16 05:27 UTC, max-underthesun commented on app/views/questions/_form.html.erb
> +<%= form_with model: @question, local: true do |form| %>
ТЗ: "Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]"

2019-01-16 05:27 UTC, max-underthesun commented on app/views/questions/_form.html.erb
> +    <%= form.collection_select :test_id, Test.all, :id, :title, prompt: true %>
строки 10 и 11 лишние - родительский тест должен задаваться с помощью правильного пути (см. коммент к 1-ой строке)

2019-01-16 05:27 UTC, max-underthesun commented on app/views/questions/_form.html.erb
> +    <%= form.text_field :body, id: :question_body %>
если нет необходимости присвоить полю какое-то специальное "ай-ди", то лучше оставлять этот параметр "на усмотрение рельс" - они прекрасно присваивают "ай-ди" самостоятельно

2019-01-16 05:27 UTC, max-underthesun commented on app/views/questions/new.html.erb
> +-->
убирай старый код перед пушем на проверку

2019-01-16 05:27 UTC, max-underthesun commented on app/views/shared/_footer.html.erb
> +<p>
футер более правильно положить не в `shared`, а в `layouts`

2019-01-16 05:27 UTC, max-underthesun commented on app/views/shared/_footer.html.erb
> +  <%= current_year %> Семенкин Павел - программист Ruby on rails <%= link_to 'Github', github_url %>
ссылки на сторонние ресурсы правильно открывать в новой закладке

2019-01-16 05:27 UTC, max-underthesun commented on app/helpers/questions_helper.rb
> +  def question_header(question, method_name)
для определения создается ресурс или редактируется
лучше использовать хелперы `.persisted?` и `.new_record?`

2019-01-16 05:27 UTC, max-underthesun commented on app/helpers/questions_helper.rb
> +  def question_header(question, method_name)
из вьюхи достаточно получать только ресурс, а "метод нейм" уже вычислять здесь - на то он и хелпер )

2019-01-16 05:27 UTC, max-underthesun commented on app/helpers/questions_helper.rb
> +    test = Test.find(question.test_id)
зачем так сложно? есть же ассоциации: `question.test`

2019-01-16 05:27 UTC, max-underthesun commented on app/helpers/application_helper.rb
> +  end
в рельсах рекомендуется использовать `Time.current` вместо `Time.now` и `Date.current` вместо `Date.today`
`.current` возвращает текущий момент времени с учетом настройки часового пояса в приложении

2019-01-16 05:27 UTC, max-underthesun commented on app/helpers/application_helper.rb
> +  end
ТЗ: "Для формирования ссылки на GitHub репозиторий: github_url(author, repo)"
обрати внимание - метод должен принимать аргументы

2019-01-16 05:27 UTC, max-underthesun commented on app/views/tests/_test.html.erb
> +  <td><%= test.questions.count %></td>
обычно управляющие ссылки делают в последних колонках таблицы, а всю остальную информацию выводят до них

2019-01-17 04:59 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +  def index; end
так совсем нужно убрать этот экшен
и из коллбека тоже

2019-01-17 04:59 UTC, max-underthesun commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
повторим комментарий ))
повторяющийся код

2019-01-17 04:59 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    redirect_to test_path
а что это за путь?
если это роут на страницу "шоу" теста, то нужен "ай-ди" теста 
подозреваю именно из-за этого редиректа у тебя ошибка на дестрое и вываливается

2019-01-17 17:44 UTC, iBublik requested changes

2019-01-17 17:44 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  def edit; end
Экшны new/create, edit/update обычно пишут парами, т.к. они логически продолжают друг друга

2019-01-17 17:44 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params)
Где связь вопроса с тестом?

2019-01-17 17:44 UTC, iBublik commented on app/helpers/application_helper.rb
> +  def github_url(author, repo)
Назови тогда github_link - у тебя метод не url возвращает, а html ссылку

2019-01-17 17:44 UTC, iBublik commented on app/helpers/questions_helper.rb
> +    test = question.test
Новый вопрос у тебя не связан с тестом, так что тут по идее nil будет

2019-01-17 17:44 UTC, iBublik commented on app/helpers/questions_helper.rb
> +      'Create New '+test.title+' Question'
Используй интерполяцию вместо конкатенации (`'a' + b` => `"a#{b}"`)

2019-01-17 17:44 UTC, iBublik commented on app/views/questions/new.html.erb
> +<h1><%= question_header(@question) %></h1>
Вынеси в паршл формы, чтоб не дублировать в new/edit

2019-01-17 17:44 UTC, iBublik commented on app/views/tests/show.html.erb
> +  <% @test.questions.each do |question| %>
Тут лучше рендерить коллекцию, как ты сделал с `@tests` в tests/index

2019-01-17 17:44 UTC, iBublik commented on app/views/layouts/application.html.erb
> +    <% csrf_meta_tags %>
Здесь должно быть `<%= csrf_meta_tags >`. Без `=` результат выполнение метода не вставляется в разметку, соответственно у тебя на странице нет CSRF тега и все запросы, выполняемые js-ом не работают. Если интересно, как связан клик по ссылке с выполнением JS, можешь написать в личку или на форуме, расскажу

2019-01-18 16:57 UTC, merged