task 9
pavels3579/ror pull request #9
Opened 2019-01-19 21:17 UTC by pavels3579

2019-01-20 12:25 UTC, iBublik requested changes

2019-01-20 12:25 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, only: %i[show edit update destroy]
Соблюдай единообразие в нейминге - выше подобный коллбек называется `set`, здесь `find`

2019-01-20 12:25 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
Где связь с вопросом?

2019-01-20 12:25 UTC, iBublik commented on app/helpers/application_helper.rb
> +    result = {}
Подсчет результата теста - бизнес-логика, ей место в моделях, никак не в хелперах
В хелпере должно быть что такое `if test_passage.success? then ... else ... end`

2019-01-20 12:25 UTC, iBublik commented on app/models/test.rb
> +  has_many :test_passages
Не забывай про dependent

2019-01-20 12:25 UTC, iBublik commented on app/models/test_passage.rb
> +  before_update :before_update_set_next_question
Этот и предыдущий коллбек делают одно и то же по сути - устанвливают _следующий вопрос_. Разница лишь в том, что считать следующим. Имеет смысл объединить их в один простой коллбек:
```ruby
def set_current_question
  self.current_question = next_question
end
```
А всю различающуюся логику поместить уже в метод `next_question`

2019-01-20 12:25 UTC, iBublik commented on app/models/test_passage.rb
> +    if correct_answer?(answer_ids)
Однострочник будет проще читаться

2019-01-20 12:25 UTC, iBublik commented on app/models/test_passage.rb
> +    correct_answers_count == answer_ids.count
> Возможен более простой способ реализации проверки правильного ответа:
>
> `correct_answers.ids.sort == answer_ids.map(&:to_i).sort`

2019-01-20 12:25 UTC, iBublik commented on app/models/test_passage.rb
> +    correct_answers_count == answer_ids.count
Только нужно учесть, что пользователь может не выбрать ни одного ответа из предложенных. Код от этого не должен падать

2019-01-20 12:25 UTC, iBublik commented on app/models/user.rb
> +    test_passages.order(id: :desc).find_by(test_id: test.id)
`find_by(test: test)`

2019-01-20 12:25 UTC, iBublik commented on app/views/test_passages/show.html.erb
> +<h2><%= @test_passage.test.questions.index(@test_passage.current_question).to_i+1 %> of <%= @test_passage.test.questions.count %></h2>
Слишком много логики для отображения подсчет номера вопроса - бизнес-логика

2019-01-20 12:25 UTC, iBublik commented on app/views/test_passages/show.html.erb
> +<h2><%= @test_passage.test.questions.index(@test_passage.current_question).to_i+1 %> of <%= @test_passage.test.questions.count %></h2>
Определенеие текущего номера вопроса неэффективно - ты грузишь все вопросы в память. Можно это сделать с помощью запроса - посмотри на код определения следующего вопроса, тут будет схожая логика.

2019-01-20 12:25 UTC, iBublik commented on config/routes.rb
> +    member do
Можно записат короче - `post :start, on: :member`

2019-01-21 04:17 UTC, max-underthesun commented on app/models/test_passage.rb
> +  end
дополнительные условия и ветвления усложняют код
здесь всего лишь нужно, чтоб в `answer_ids` всегда был массив
для этого можно использовать запись:
```ruby
Array(answer_ids)
```
в этом случае мы получаем гарантию, что на выходе будет массив

код метода получится в одну строчку, без дополнительных условий:
```ruby
def correct_answer?(answer_ids)
  correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
end
```

2019-01-21 04:17 UTC, max-underthesun commented on app/views/test_passages/result.html.erb
> +  <span style="color: green" > <%= @test_passage.percent_correct %></span>
стилизацию лучше делать через `css`:
создать классы, к примеру `test_passage.succes`, `test_passage.fail` и там все описать

2019-01-21 04:17 UTC, max-underthesun commented on app/models/test_passage.rb
> +    (self.correct_questions*100/questions_count).round
селф лишний, не хватает пробелов вокруг "умножить"

и лучше, чтоб при делении одно число было нецелым (`float`)
сейчас у тебя результат - `integer`, т.е. происходит округление
для подсчета баллов лучше быть более точным
(соответственно `round` правильней убрать)

если целое число нужно во вьюхе, то более правильным будет привести к целому именно там (или в отдельном хелпере)

2019-01-21 14:47 UTC, merged